name: Install
description: Install PNPM, Node.js, and dependencies
runs:
  using: composite
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile