name: Audit Dependencies

on:
  workflow_call:

jobs:
  audit:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6
      
      - name: Audit Dependencies
        run: pnpm audit --prod --audit-level critical # TODO: lower this