name: Lint

on:
  workflow_call:

jobs:
  audit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install
        uses: ./.github/actions/install
      
      - name: Lint
        run: pnpm lint:packages