name: Test deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/pages-deploy.yaml
      - .github/workflows/pages-test-deploy.yaml

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Install
        uses: ./.github/actions/checkout-install

      - name: Test Build docs
        working-directory: docs
        run: pnpm build