name: Publish

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [./.github/workflows/publish.yml, packages/**]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install dependencies
        # https://github.com/pnpm/pnpm/issues/3664
        run: pnpm install --no-frozen-lockfile && git add .

      - name: Compile TypeScript
        run: pnpm build

      # This step will create or update the PR, "Package Versions". When that
      # PR is merged, it will release to NPM. Maintainers should ensure PR is
      # passing all checks before merging PR since audit, lint, test doesn't run
      # in this workflow
      - name: Create PR, Update PR, or Release to NPM
        uses: changesets/action@v1
        with:
          # publish command will only run upon merge of PR created by changesets.
          # publish doesn't run on every push to main
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}