name: Release

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/release.yaml

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: release
    needs: [build, lint, test]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install
        uses: ./.github/actions/install

      - name: Download gb-lib build artifact
        uses: actions/download-artifact@v2
        with:
          name: gb-lib-build-artifact
          path: packages/gb-lib/lib

      - name: Download gboost build artifact
        uses: actions/download-artifact@v2
        with:
          name: gboost-build-artifact
          path: packages/gboost/lib

      # This step will create or update the PR, "chore: update versions" if 
      # main it directly committed to, or it will publish the NPM package
      # if the "chore: update versions" PR is merged into main
      - name: Create and Publish Versions
        uses: changesets/action@v1
        with:
          # by default in CI environment pnpm i run siwth --frozen-lockfile but
          # since the version in package.json's have been changed by changeset
          # it throws an error. Therefore we allow pnpm to update lockfile
          # (no deps are being updated) and then add the changes. Run git add .
          # because later changesets will commit changes for us 
          # https://github.com/pnpm/pnpm/issues/3664
          version: pnpm exec changeset version && pnpm i --no-frozen-lockfile && git add .
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}