name: Test

on:
  workflow_call:

jobs:
  audit:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install
        uses: ./.github/actions/install
      
      - name: Test
        run: pnpm test:packages